name: macOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.3'
        channel: 'stable'
    
    - name: Enable macOS desktop
      run: flutter config --enable-macos-desktop
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build macOS
      run: flutter build macos --release
    
    - name: Create DMG
      run: |
        npm install -g appdmg
        mkdir -p SnapPay-macOS
        cp -R build/macos/Build/Products/Release/SnapPay.app SnapPay-macOS/
        zip -r SnapPay-macOS.zip SnapPay-macOS/
    
    - name: Upload macOS Build
      uses: actions/upload-artifact@v3
      with:
        name: macos-release
        path: SnapPay-macOS.zip