name: Test Windows Build

on:
  workflow_dispatch:

jobs:
  build-test:
    name: Build Test Flutter App
    runs-on: windows-latest

    steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'

    - name: Create test app
      run: flutter create test_app

    - name: Build Windows Release
      run: |
        cd test_app
        flutter build windows --release

    - name: List build output
      run: dir test_app\build\windows\x64\runner\Release\
      shell: cmd

    - name: Create ZIP
      run: |
          cd test_app\build\windows\x64\runner\Release
          Compress-Archive -Path * -DestinationPath 
          ..\..\..\..\..\..\TestApp-Windows.zip
      shell: powershell

    - name: Upload Test App
      uses: actions/upload-artifact@v4
      with:
        name: test-app-windows
        path: TestApp-Windows.zip
        retention-days: 7
