name: Windows Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.3'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Windows
      run: flutter build windows --release
    
    - name: Copy Visual C++ Redistributables
      run: |
        Copy-Item "C:\Windows\System32\msvcp140.dll" -Destination "build\windows\x64\runner\Release\" -ErrorAction SilentlyContinue
        Copy-Item "C:\Windows\System32\vcruntime140.dll" -Destination "build\windows\x64\runner\Release\" -ErrorAction SilentlyContinue
        Copy-Item "C:\Windows\System32\vcruntime140_1.dll" -Destination "build\windows\x64\runner\Release\" -ErrorAction SilentlyContinue
    
    - name: List build contents
      run: |
        Write-Host "Contents of Release folder:"
        Get-ChildItem -Path build\windows\x64\runner\Release\ -Recurse | Format-Table Name, Length, LastWriteTime
    
    - name: Upload Windows Build
      uses: actions/upload-artifact@v3
      with:
        name: windows-release
        path: build/windows/x64/runner/Release/